INSERT INTO counties (name, shortName) VALUES 
('Asotin', 'ASOT'), 
('Benton', 'BENT'), 
('Chelan', 'CHEL'),
('Clallam', 'CLAL'),
('Clark', 'CLAR'),
('Columbia', 'COLU'),
('Cowlitz', 'COWL'),
('Douglas', 'DOUG'),
('Ferry', 'FERR'),
('Franklin', 'FRAN'),
('Grant', 'GRAN'),
('Grays Harbor', 'GRAY'),
('Island', 'ISLA'),
('Jefferson', 'JEFF'),
('King', 'KING'),
('Kitsap', 'KITS'),
('Kittitas', 'KITT'),
('Klickitat', 'KLIC'),
('Lewis', 'LEWI'),
('Lincoln', 'LINC'),
('Mason', 'MASO'),
('Okanogan', 'OKAN'),
('Pacific', 'PACI'),
('Pend Oreille', 'PEND'),
('Pierce', 'PIER'),
('San Juan', 'SAN'),
('Skagit', 'SKAG'),
('Skamania', 'SKAM'),
('Snohomish', 'SNOH'),
('Spokane', 'SPOK'),
('Stevens', 'STEV'),
('Thurston', 'THUR'),
('Walla Walla', 'WALL'),
('Whatcom', 'WHAT'),
('Whitman', 'WHIT'),
('Yakima', 'YAKI');